### ISSUE TITLE
Usabilty problems and suggestions for planning mode

### ISSUE THREAD

**Issue by CarstenBaumannH** [citybound/citybound#114]
I found some usability issues which could be desinged better.

1. Number of lanes: When creating a new road for, example with 4 lanes, and creating another new road wihch is not conected to the first road (planned or implemented), the number of lanes falls back to default (2 lines). It might be better to keep the choosen number of lanes.
2. It is really difficult to find the right point / area on an implemented or planned road to expand it. It would be better if this point / area is bigger or it gets an icon next to the end of the road (when the courser is at the road) which makes it easier to expand the road.

**Comment by aeickhoff** [comment]
Both really good points, could you please create separate issues for them with descriptive titles so its easier to fix them? Thanks!
