### ISSUE TITLE
Grid not working

### ISSUE THREAD

**Issue by kingoflolz** [citybound/citybound#119]
Pressing G, enter and C results in a grid but no cars

Reproduced on Linux and Windows 10

**Comment by reneraab** [comment]
I can confirm this on Linux.
My terminal window get's spammed with this output:
```
ID 1_0_28 is not a destination yet
ID 1_0_79 is not a destination yet
[... lot's of these ...]
```

**Comment by aeickhoff** [comment]
This bug was introduced in #108, basically no intersections are created for the long roads of the grid (which is very stupid of me to not force *and* to not test), I will fix it today

**Comment by aeickhoff** [comment]
This should work in the new release! (0.1.2)
