### ISSUE TITLE
Weird behavior when building uncommitted plans

### ISSUE THREAD

**Issue by kingoflolz** [citybound/citybound#120]
Not sure what is meant to happen, but if you plan some segments, and then hit enter, everything will be blank until you move the mouse, where the uncommitted plans will still be there.

**Comment by aeickhoff** [comment]
do you press enter *while* drawing a stroke?

**Comment by kingoflolz** [comment]
yeah

**Comment by aeickhoff** [comment]
Feels better if you can immediately press enter even during a stroke, so I implemented it like that!
