### ISSUE TITLE
Undo with German keyboard layout using Cmd+Y

### ISSUE THREAD

**Issue by awendt** [citybound/citybound#143]
## Steps to reproduce

- run on macOS Sierra
- set keyboard layout to German (Y and Z are switched)
- press Cmd+Z

## Expected behavior

- undo last action

## Actual behavior

- nothing happens
- undo is on Cmd+Y

Most applications out there use Cmd+Z, and my keyboard layout usually doesn't make a difference. Having no idea about Rust whatsoever, it seems Citybound's listening to a specific physical key to be pressed.

**Comment by reenenlaurie** [comment]
Close this, it's not applicable anymore

**Comment by aeickhoff** [comment]
Thanks for the reminder!
