### ISSUE TITLE
Simulation panic - called option::Unwrap() on a None value

### ISSUE THREAD

**Issue by nimper** [citybound/citybound#146]
I think the situation should speak for itself here. Not sure if it's related to another bug.

OS is Windows 7

![image](https://cloud.githubusercontent.com/assets/7697539/22712419/58f186e6-ed4a-11e6-9e35-6f9de36a9ba7.png)

**Comment by graup** [comment]
I just triggered the same (?) bug with this setup:

<img width="1383" alt="screen shot 2017-02-12 at 12 10 47" src="https://cloud.githubusercontent.com/assets/898549/22859385/7aefaef0-f11c-11e6-8c79-3a4f4e241aa1.png">
