### ISSUE TITLE
Basic decision-making based on resources

### ISSUE THREAD

**Issue by aeickhoff** [citybound/citybound#148]
- [x] Come up a small set of resources that covers as much of "life" as possible
- [x] Divide resource acquisition into 3 categories:
   - "deal breaking"
      - physical health
      - mental health
      - hunger
      - money (for businesses)
   - "basic, recurring"
      - job security (for people)
      - money (for people)
      - stock (for people & businesses)
   - "spontaneous, nice to have"
      - closeness to nature
      - luxury goods
      - excercise
      - social life
      - entertainment

- [x] Come up with a model for Activities that are resource trades
   - rate of depletion/fulfilment for each resource
   - [x] how to factor in travel time

- [x] Figure out how short-term and long-term planning work and interact
   - short-term planning: care about and fix absolute resource values   
   - long-term planning: care about and fix resource rates over time
      - "​'at this rate, i will be unhappy in 4 months. With my current time / money situation what can i do within 4 months that﻿ prevents that threshold from being reached"
      - acquisition of new household/business items that change their effectivity for certain activities, or might even provide new activities both at the household/business or completely different locations (skateboard -> "skate park")
      - moving to a different location
      - change of recurring daily schedule?

**Comment by mallenwho** [comment]
This is a very crude representation of Prison Architect needs: each bar can shift in time depending on how long since the need was fulfilled and how the need is being fulfilled. And the different severities are a good way to control behavoir to focus on whatever is most important. It builds in a boredom function too!

http://devwiki.introversion.co.uk/pa/images/f/f1/Needs_report_a36.png

**Comment by AzemOcram** [comment]
I suggest you change "closeness to nature" to 'environment.' Then it can have subcategories of 'nature,' 'art,' and 'comfort.'

**Comment by zakerunner** [comment]
^^ That's good because then it can more obviously incorporate air, water, and noise pollution, assuming those will eventually be included

**Comment by raceman95** [comment]
Moving to a different location is basically modeled by the same as "buying a skateboard". It might cost a lot of money and a whole day of time (which is nearly 2 weeks if you do 1 week per season), but could allow someone to possibly walk to their favorite park or restaurant or work instead of driving.

**Comment by nosh59** [comment]
It would be interesting if certain citizens value some of the "nice to have needs" over others. For example, an athletic citizen would value "exercise" the most, a socialite would value "social life" the most, or a nature-loving citizen would value "closeness to nature" the most. Those needs could also, be randomly prioritized for each citizen.

As of goods, I think they should also vary in quality. Lower quality goods are more affordable, but they are less effective and more likely to break than higher quality goods. Once purchased, the good would have two values; "effectiveness" and "chance of breaking." The good's effectiveness would slowly decrease linearly over time, and it's chance of breaking would slowly increase exponentially over time.

A good could also be classified by where they can fulfill a need (at home or anywhere (including in-transit)).

For example: 
At home goods: Computer (entertainment, social life), TV (entertainment), Food (hunger), Phone (social life), etc.

Goods used anywhere: Cellphone or Tablet (entertainment, social life), Portable Food (hunger), Medicine (mental and/or physical health), Book (entertainment), etc.

Ex. A citizen buys a low quality TV for a low price at an electronic store. The TV fulfills little "entertainment" and "luxury goods" when the citizen is at home. After a couple of years, the TV's effects lowers, and has a 50% chance of breaking. Once it breaks, the TV loses all effects and the citizen can buy a better TV or get it repaired.

Also, if I may add one more need, it would be home environment, which would be fulfilled by buying "cleaning products" at stores

**Comment by AzemOcram** [comment]
I also view exercise as an activity that increases physical health moderately, mental health slightly, and entertainment moderately (depending on how and where the exercise is done). It doesn't seem like an independent need but rather a subcategory of entertainment that is good for health.
