### ISSUE TITLE
Find a model for buildings housing families and businesses

### ISSUE THREAD

**Issue by aeickhoff** [citybound/citybound#150]
- [ ] ~~Limited amount of space~~ -> #206
- [ ] ~~Restricted for certain use (residential, some kinds of businesses)~~ -> #206
- [x] Have a simple kind of physical location (connection to a road)
- [x] Have a simple graphical representation

**Comment by mallenwho** [comment]
Once upon a time, this game started as a promise for completely procedural architecture.

Then came along a build with functional procedural gable blocks of various sizes, and multistorey blocks for high street shopping. They were blank and clean and minimalist and good looking.

Could we bring back some parts of that? 
I really hope procedural architecture isn't a lost idea! And this would be a good start in that right direction!
