### ISSUE TITLE
index is out of bounds 

### ISSUE THREAD

**Issue by monk-e-boy** [citybound/citybound#160]
I was using the blue selection to move a bit of road, then an error occurred. Maybe my selection was close to a anchor node?

![explorer_2017-02-15_23-29-08](https://cloud.githubusercontent.com/assets/17924807/23000100/d7870c46-f3d6-11e6-8b59-d093b905f3fc.png)

**Comment by LogoiLab** [comment]
I've got a similar error but on startup. It quickly fork bombs my computer with the auto-open editor feature (It occurs in an event loop that refuses to panic is my guess hence spamming the auto-open function). Maybe only let the auto-open occur once?
[cb_last_error.txt](https://github.com/citybound/citybound/files/1463571/cb_last_error.txt)

**Comment by aeickhoff** [comment]
@LogoiLab, I created a separate issue (#229) for what you described, it seems unrelated to this to me. Sorry about the fork bomb, I'll make sure to only open the error file once (#230)

**Comment by aeickhoff** [comment]
The next version of the game will have a completely rewritten road logic, so this error should not occur again. If something similar happens, please open a new issue then.
