### ISSUE TITLE
Camera jumps when shifting view

### ISSUE THREAD

**Issue by Herbstein** [citybound/citybound#187]
The camera will jump around seemingly randomly along the movement axis when the camera is moved. 
[I've recorded a video of it](https://youtu.be/LDcXuraOotY).

In the above video I'm holding `shift` and moving my mouse. I continue holding shift after the road disappears from view. I have looked at the `ShiftAbsolute` function in `stagemaster`, but it seems to be working correctly. I suspect the fault lies somewhere in the input handling.

**Comment by Herbstein** [comment]
I should also note that this problem persists on both the `master` and the `economy` branches.

**Comment by aeickhoff** [comment]
Oh, good catch, thanks! Yeah, I had a suspicion that the new solution might have some instabilities, I'll look into it.
