### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by mijgame** [citybound/citybound#223]
Was just trying things out with roads. Dragging very long road segments in plan-mode in order to try to reproduce the memory leak error we were trying to debug on stream.
Then this error happened:

```
WHAT HAPPENED:
called `Option::unwrap()` on a `None` value

WHERE IT HAPPENED:
at src\libcore\option.rs, line 335

WHERE EXACTLY:
stack backtrace:
   0:     0x7ff6015def52 - backtrace::backtrace::trace<closure>
                        at C:\Users\Lex\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.3\src\backtrace\mod.rs:41
   1:     0x7ff6015dd343 - backtrace::capture::Backtrace::new
                        at C:\Users\Lex\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.3\src\capture.rs:62
   2:     0x7ff601316855 - citybound::core::init::set_error_hook::{{closure}}
                        at D:\Bibliotheek\Downloads\citybound\game\core\init.rs:60
   3:     0x7ff601606304 - std::panicking::rust_panic_with_hook
                        at C:\projects\rust\src\libstd\panicking.rs:578
   4:     0x7ff601606109 - std::panicking::begin_panic<alloc::string::String>
                        at C:\projects\rust\src\libstd\panicking.rs:538
   5:     0x7ff601606052 - std::panicking::begin_panic_fmt
                        at C:\projects\rust\src\libstd\panicking.rs:522
   6:     0x7ff601605fc0 - std::panicking::rust_begin_panic
                        at C:\projects\rust\src\libstd\panicking.rs:498
   7:     0x7ff60160cb5f - core::panicking::panic_fmt
                        at C:\projects\rust\src\libcore\panicking.rs:71
   8:     0x7ff60160ca8f - core::panicking::panic
                        at C:\projects\rust\src\libcore\panicking.rs:51
   9:     0x7ff601481787 - stagemaster::user_interface::{{impl}}::submitted
                        at D:\Bibliotheek\Downloads\citybound\engine\stagemaster\src\user_interface\mod.rs:551
  10:     0x7ff6014c87fb - kay::swarm::Swarm<stagemaster::user_interface::UserInterface>::dispatch_packet<stagemaster::user_interface::UserInterface,monet::renderer::control::kay_auto::MSG_TargetProvider_submitted,closure>
                        at D:\Bibliotheek\Downloads\citybound\engine\kay\src\swarm.rs:262
  11:     0x7ff6014650be - kay::actor_system::{{impl}}::add_handler::{{closure}}<stagemaster::user_interface::UserInterface,monet::renderer::control::kay_auto::MSG_TargetProvider_submitted,closure>
                        at D:\Bibliotheek\Downloads\citybound\engine\kay\src\actor_system.rs:141
  12:     0x7ff601528b46 - kay::actor_system::ActorSystem::single_message_cycle
                        at D:\Bibliotheek\Downloads\citybound\engine\kay\src\actor_system.rs:240
  13:     0x7ff60152c818 - std::panic::{{impl}}::call_once<(),closure>
                        at C:\projects\rust\src\libstd\panic.rs:295
  14:     0x7ff601607432 - panic_unwind::__rust_maybe_catch_panic
                        at C:\projects\rust\src\libpanic_unwind\lib.rs:99
  15:     0x7ff60152eb39 - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at C:\projects\rust\src\libstd\panicking.rs:464
  16:     0x7ff60152cab3 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at C:\projects\rust\src\libstd\panic.rs:363
  17:     0x7ff601528d03 - kay::actor_system::ActorSystem::process_all_messages
                        at D:\Bibliotheek\Downloads\citybound\engine\kay\src\actor_system.rs:265
  18:     0x7ff601400866 - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at C:\projects\rust\src\libstd\sys_common\backtrace.rs:131
  19:     0x7ff601607432 - panic_unwind::__rust_maybe_catch_panic
                        at C:\projects\rust\src\libpanic_unwind\lib.rs:99
  20:     0x7ff601306a85 - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at C:\projects\rust\src\libstd\panicking.rs:464
  21:     0x7ff60140a5e7 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at C:\projects\rust\src\liballoc\boxed.rs:762
  22:     0x7ff6016048ac - std::sys::imp::thread::{{impl}}::new::thread_start
                        at C:\projects\rust\src\libstd\sys\windows\thread.rs:54
  23:     0x7ff9b3892774 - BaseThreadInitThunk
```

I'm not familiar enough with the code involved to really investigate further I'm afraid. Hope this can be of use.

**Comment by aeickhoff** [comment]
That's a new one (at least for the scenario you described), thanks for reporting.

**Comment by aeickhoff** [comment]
I assume Windows?

**Comment by ferdinand0101** [comment]
Probably i had the same issue on windows


WHAT HAPPENED:
called `Option::unwrap()` on a `None` value

WHERE IT HAPPENED:
at src\libcore\option.rs, line 335

WHERE EXACTLY:
stack backtrace:
   0:     0x7ff76292bb72 - <no info>
   1:     0x7ff762929fd3 - <no info>
   2:     0x7ff7625dbc17 - <no info>
   3:     0x7ff762953214 - <no info>
   4:     0x7ff762953019 - <no info>
   5:     0x7ff762952f62 - <no info>
   6:     0x7ff762952ed0 - <no info>
   7:     0x7ff7629594cf - <no info>
   8:     0x7ff7629593ff - <no info>
   9:     0x7ff762821a40 - <no info>
  10:     0x7ff76281095d - <no info>
  11:     0x7ff7627e99ce - <no info>
  12:     0x7ff76287d743 - <no info>
  13:     0x7ff762873948 - <no info>
  14:     0x7ff762954342 - <no info>
  15:     0x7ff762877389 - <no info>
  16:     0x7ff7628758e3 - <no info>
  17:     0x7ff76287d8e3 - <no info>
  18:     0x7ff76272e273 - <no info>
  19:     0x7ff762954342 - <no info>
  20:     0x7ff7626a6c95 - <no info>
  21:     0x7ff762747d27 - <no info>
  22:     0x7ff7629517cc - <no info>
  23:     0x7ffdfc183034 - BaseThreadInitThunk

**Comment by ferdinand0101** [comment]
WHAT HAPPENED:
called `Option::unwrap()` on a `None` value

WHERE IT HAPPENED:
at src\libcore\option.rs, line 335

WHERE EXACTLY:
stack backtrace:
   0:     0x7ff76292bb72 - <no info>
   1:     0x7ff762929fd3 - <no info>
   2:     0x7ff7625dbc17 - <no info>
   3:     0x7ff762953214 - <no info>
   4:     0x7ff762953019 - <no info>
   5:     0x7ff762952f62 - <no info>
   6:     0x7ff762952ed0 - <no info>
   7:     0x7ff7629594cf - <no info>
   8:     0x7ff7629593ff - <no info>
   9:     0x7ff762821a40 - <no info>
  10:     0x7ff76281095d - <no info>
  11:     0x7ff7627e99ce - <no info>
  12:     0x7ff76287d743 - <no info>
  13:     0x7ff762873948 - <no info>
  14:     0x7ff762954342 - <no info>
  15:     0x7ff762877389 - <no info>
  16:     0x7ff7628758e3 - <no info>
  17:     0x7ff76287d8e3 - <no info>
  18:     0x7ff76272e273 - <no info>
  19:     0x7ff762954342 - <no info>
  20:     0x7ff7626a6c95 - <no info>
  21:     0x7ff762747d27 - <no info>
  22:     0x7ff7629517cc - <no info>
  23:     0x7ffdfc183034 - BaseThreadInitThunk>

**Comment by ferdinand0101** [comment]
might have something todo with this 

transfer lane not connected for obstacles yet
^^from console

**Comment by aeickhoff** [comment]
This will be obsolete in the next version which will fully rely on a browser UI
