### ISSUE TITLE
Simulation Broke - Roads Related I think

### ISSUE THREAD

**Issue by reenenlaurie** [citybound/citybound#241]
I am on Windows 7 HP Laptop.  Nothing special about it.

I think I was building a road - trying to connect two pieces that were close but not connected.

I don't really have more detailed information.

SIMULATION BROKE :(

HOW TO REPORT BUGS:
https://github.com/citybound/citybound/blob/master/CONTRIBUTING.md#reporting-bugs

WHAT HAPPENED:
index out of bounds: the len is 7 but the index is 7

WHERE IT HAPPENED:
at game\transport\microtraffic\mod.rs, line 438

WHERE EXACTLY:
stack backtrace:
   0:        0x13fc5bb72 - <no info>
   1:        0x13fc59fd3 - <no info>
   2:        0x13f90bc17 - <no info>
   3:        0x13fc83214 - <no info>
   4:        0x13fc83019 - <no info>
   5:        0x13fc82f62 - <no info>
   6:        0x13fc82ed0 - <no info>
   7:        0x13fc894cf - <no info>
   8:        0x13fc89481 - <no info>
   9:        0x13f9f0845 - <no info>
  10:        0x13f9700f8 - <no info>
  11:        0x13fbad743 - <no info>
  12:        0x13fba3948 - <no info>
  13:        0x13fc84342 - <no info>
  14:        0x13fba7389 - <no info>
  15:        0x13fba58e3 - <no info>
  16:        0x13fbad8e3 - <no info>
  17:        0x13fa5e1f5 - <no info>
  18:        0x13fc84342 - <no info>
  19:        0x13f9d6c95 - <no info>
  20:        0x13fa77d27 - <no info>
  21:        0x13fc817cc - <no info>
  22:         0x777b59cd - BaseThreadInitThunk

**Comment by reenenlaurie** [comment]
My full console log:

[cb_last_error.txt](https://github.com/citybound/citybound/files/1538276/cb_last_error.txt)

**Comment by chances** [comment]
> the len is 7 but the index is 7

Looks like some kinda pesky off-by-one error. 😛

**Comment by BadFactor** [comment]
Got the same issue i think, just want to paint the road, with grid system enabled key "g", mouse click to generate the road, if i do the rounded road it wont work anymore!

WIN 10 FALL CREATORS UPDATE!
AMD FX 6300+
RADEON R9 270X
SSD 256 GB

SIMULATION BROKE :(

HOW TO REPORT BUGS:
https://github.com/citybound/citybound/blob/master/CONTRIBUTING.md#reporting-bugs

WHAT HAPPENED:
Failed to build the 2d convex hull of this point cloud.

WHERE IT HAPPENED:
at C:\Users\Anselm Eickhoff\.cargo\registry\src\github.com-1ecc6299db9ec823\ncollide_transformation-0.5.0\convex_hull.rs, line 763

WHERE EXACTLY:
stack backtrace:
   0:     0x7ff74c26bb72 - <no info>
   1:     0x7ff74c269fd3 - <no info>
   2:     0x7ff74bf1bc17 - <no info>
   3:     0x7ff74c293214 - <no info>
   4:     0x7ff74bfe6c5a - <no info>
   5:     0x7ff74be9fa99 - <no info>
   6:     0x7ff74bfff3e1 - <no info>
   7:     0x7ff74be94490 - <no info>
   8:     0x7ff74c0ac432 - <no info>
   9:     0x7ff74c0c404e - <no info>
  10:     0x7ff74c01f97c - <no info>
  11:     0x7ff74bfcc199 - <no info>
  12:     0x7ff74bedf436 - <no info>
  13:     0x7ff74c1bd743 - <no info>
  14:     0x7ff74c1b3948 - <no info>
  15:     0x7ff74c294342 - <no info>
  16:     0x7ff74c1b7389 - <no info>
  17:     0x7ff74c1b58e3 - <no info>
  18:     0x7ff74c1bd8e3 - <no info>
  19:     0x7ff74c06e20c - <no info>
  20:     0x7ff74c294342 - <no info>
  21:     0x7ff74bfe6c95 - <no info>
  22:     0x7ff74c087d27 - <no info>
  23:     0x7ff74c2917cc - <no info>
  24:     0x7ffad0241fe4 - BaseThreadInitThunk

**Comment by MrPetovan** [comment]
Same here, steps to reproduce:
- Open simulation
- Press G
- Click once to make a straight road
- Click a second time to make the road loop on itself

Mac OS X Sierra 10.12.6
MacBook Pro (Retina, 15-inch, Early 2013)
2.4 GHz Intel Core i7
16 GB 1600 MHz DDR3
NVIDIA GeForce GT 650M 1024 MB
Intel HD Graphics 4000 1536 MB

`cb_last_error.txt`:
```
WHAT HAPPENED:
Failed to build the 2d convex hull of this point cloud.

WHERE IT HAPPENED:
at /Users/[redacted]/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_transformation-0.5.0/convex_hull.rs, line 763

WHERE EXACTLY:
stack backtrace:
   0:        0x101fb844e - backtrace::backtrace::trace::h1e071f7475579ad6
   1:        0x101fb62cc - backtrace::capture::Backtrace::new::h47fff0208a22eb3b
   2:        0x101d191fb - citybound::core::init::set_error_hook::_$u7b$$u7b$closure$u7d$$u7d$::h8906bc1c98c85a8d
   3:        0x101fd4831 - std::panicking::rust_panic_with_hook::h2ec98db505607dac
   4:        0x101da8f17 - std::panicking::begin_panic::h949bcf9b0490df96
   5:        0x101b9de52 - ncollide_transformation::convex_hull::convex_hull2_idx::h0df0becf9247907d
   6:        0x101d17431 - descartes::path::convex_hull::h5b1f1654cbeda09c
   7:        0x101b938ac - _$LT$compact..compact_vec..CompactVec$LT$T$C$$u20$A$GT$$u20$as$u20$core..iter..traits..FromIterator$LT$T$GT$$GT$::from_iter::h84355cafb0ebd76d
   8:        0x101de7544 - citybound::transport::planning::road_result_steps::find_intersections::hb9a5d829a9398568
   9:        0x101df749c - citybound::planning::plan::Plan::get_result::h217999c43e006ac1
  10:        0x101d46e17 - citybound::planning::materialized_reality::MaterializedReality::simulate::hc72ced287cd1a6ce
  11:        0x101c59d3b - _$LT$kay..swarm..Swarm$LT$A$GT$$GT$::dispatch_packet::h1f3ec307110918f0
  12:        0x101bd64dd - kay::actor_system::ActorSystem::add_handler::_$u7b$$u7b$closure$u7d$$u7d$::h96c5fe051295347c
  13:        0x101efca20 - kay::actor_system::ActorSystem::single_message_cycle::h80316011f578ee66
  14:        0x101ef7017 - _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h0a7853407cc7589c
  15:        0x101fdfb7c - __rust_maybe_catch_panic
  16:        0x101ef3f87 - std::panicking::try::hed42753cc33322e4
  17:        0x101ef8d3d - std::panic::catch_unwind::h237d3c5ab9aabdb0
  18:        0x101efcb9d - kay::actor_system::ActorSystem::process_all_messages::ha8a5a8656dbed9c7
  19:        0x101d1849f - citybound::core::init::ensure_crossplatform_proper_thread::hc0b20e6835400548
  20:        0x101fdfb7c - __rust_maybe_catch_panic
  21:        0x101fd4cf8 - std::rt::lang_start::h117e7b15e25564f6
```

<img width="2032" alt="screen shot 2018-02-13 at 11 00 56 am" src="https://user-images.githubusercontent.com/925415/36159774-977ba41e-10ad-11e8-83f5-16c4b77c03fb.png">
The point where roads overlap is where I tried to make it loop on itself.

**Comment by aeickhoff** [comment]
This should not happen in the next version anymore, since it will use a rewritten road logic. If something similar pops up again, please submit a new issue then.
