### ISSUE TITLE
clippy dependency?

### ISSUE THREAD

**Issue by martinlindhe** [citybound/citybound#243]
Hi! Checking out the project, I ran into #235 and got to ask;

How come clippy is a dependency of the project?
No code seems to be used, and dropping it would fix #235.

Invoking something like `cargo install clippy && cargo clippy` in https://github.com/citybound/citybound/blob/master/.travis.yml should help you guard against any clippy issues hitting master.

From https://github.com/rust-lang-nursery/rust-clippy#usage:

> Since this is a tool for helping the developer of a library or application write better code, it is recommended not to include clippy as a hard dependency.

Another option is to make clippy an optional feature (change https://github.com/citybound/citybound/blob/master/Cargo.toml#L68) etc, but I am guessing you want to keep people from submitting code with clippy issues?

If that is the intention, I think it should happen in CI instead.

**Comment by aeickhoff** [comment]
Clippy is no longer a direct dependency. Thanks!
