### ISSUE TITLE
Runtime Error immediately upon launching "gl function not loaded"

### ISSUE THREAD

**Issue by kovartravis** [citybound/citybound#252]
`$ cargo run --release
    Finished release [optimized + debuginfo] target(s) in 0.1 secs
     Running `target\release\citybound.exe`
["target\\release\\citybound.exe"]
All mapped
thread '<unnamed>' panicked at 'gl function was not loaded', C:\Users\Travis\citybound\target\release\build\glium-8f63ed3a53699cd3\out/gl_bindings.rs:2531:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src\libcore\result.rs:916:4
error: process didn't exit successfully: `target\release\citybound.exe` (exit code: 101)`

With RUST_BACKTRACE=1
`$ cargo run --release RUST_BACKTRACE=1
    Finished release [optimized + debuginfo] target(s) in 0.1 secs
     Running `target\release\citybound.exe RUST_BACKTRACE=1`
["target\\release\\citybound.exe", "RUST_BACKTRACE=1"]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src\libcore\result.rs:916:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src\libcore\result.rs:916:4
error: process didn't exit successfully: `target\release\citybound.exe RUST_BACKTRACE=1` (exit code: 101)`

**Comment by aeickhoff** [comment]
This will be obsolete in the next version, which will fully rely on a browser UI.
