### ISSUE TITLE
fails to start on linux with wayland

### ISSUE THREAD

**Issue by ibotty** [citybound/citybound#253]
A version just now compiled from git.

```
$ citybound 
["citybound"]
All mapped
thread 'main' panicked at 'Library libwayland-egl.so could not be loaded.', libcore/option.rs:917:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

When symbolic linking libwayland-egl.so.1 to libwayland-egl.so, it fails at the following error.

```
$ citybound 
["citybound"]
All mapped
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlutinCreationError(NotSupported)', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by ibotty** [comment]
See tomaka/glutin#949

**Comment by daboross** [comment]
To anyone looking to fix this: I would recommend setting the env variable `WINIT_UNIX_BACKEND=x11` before starting glutin/glium. 

Running `export WINIT_UNIX_BACKEND=x11` before running it fixes it for me.

See https://github.com/tomaka/winit/issues/305.

**Comment by aeickhoff** [comment]
This will be obsolete in the next version, which will fully rely on a browser UI.
