### ISSUE TITLE
Remove the clippy plugin usage

### ISSUE THREAD

**Issue by oli-obk** [citybound/citybound#264]
We're removing the plugin interface from clippy, because it will be removed from rustc at some point anyway.

Would it be possible for you to use `cargo clippy` instead of having a dependency on `clippy` in your `Cargo.toml`? The `cargo-clippy` feature allows you to add lint attributes like allow/warn without affecting building without cargo-clippy.

**Comment by aeickhoff** [comment]
Thanks for bringing it up and thanks to @o01eg for implementing it :)
