### ISSUE TITLE
Open wiki page on launch

### ISSUE THREAD

**Issue by aeplay** [citybound/citybound#28]

**Comment by kingoflolz** [comment]
I think this is already implemented in demo, although it might be nice to have a more persistent location than /tmp, perhaps I will look into storing that flag and the settings in a permanent folder

**Comment by MiniDigger** [comment]
would that mean that every time you open the demo a new tab in your browser would open with the wiki? or would it be somehow embedded into the game?

**Comment by kingoflolz** [comment]
Currently, it opens the wiki page on first launch (which is what I assume the issue was talking about), however, depending on your OS setup and stuff might show you the wiki page again if you reboot, which is what I am thinking of addressing
