### ISSUE TITLE
React complains about no dead code elimination

### ISSUE THREAD

**Issue by aeickhoff** [citybound/citybound#288]

**Comment by aeickhoff** [comment]
Turns out this exception can only happen if React DevTools are active. Won'tfix!

**Comment by chriswingler** [comment]
Just ran into this issue.  Do you know how detect if React DevTools is running, and display a warning about disabling it?

**Comment by aeplay** [comment]
Added a workaround for this in cba41c61c86f3013de57ed8e416b69d984821825
