### ISSUE TITLE
Crash while "adjusting" a road

### ISSUE THREAD

**Issue by reenenlaurie** [citybound/citybound#297]
[cb_last_error.txt](https://github.com/citybound/citybound/files/2408270/cb_last_error.txt)

![2018-09-23_022133](https://user-images.githubusercontent.com/1115659/45922872-c8bee580-bed7-11e8-9692-8ffc773f706c.png)

The screenshot tells most of the story, but essentially I was trying to drag a road that maybe can't be dragged over a crossing?  I'll see if I can reproduce.

Edit: a later issue was that this bug made that launching a new game didn't work.  (after pressing ctrl-C in the console it started to run)

**Comment by aeickhoff** [comment]
The error message from your file seems like an earlier error message unrelated to this crash. Most likely you're experiencing the error #301. I'll close this as a duplicate.
