### ISSUE TITLE
Try waffle.io

### ISSUE THREAD

**Issue by ssokolow** [citybound/citybound#30]
Since you seem to be using GitHub Issues for task-tracking, I think you'd like waffle.io.

It presents a customizable set of your Issues tags as columns in a Trello-like view. 

Here's what this repo looks like with the defaults they use for projects with no associated accounts:
https://waffle.io/citybound/citybound

Click the issue number in the top-left corner of a card to see more.

(Yes, you can use it to create/edit/delete things instead of the normal GitHub Issues UI when you're logged in. They also offer a badge you can embed into your README to show the number of tasks currently sitting in a column of your choice.)

They also recently added progress metrics, to help you keep track of yourself:
https://waffle.io/citybound/citybound/metrics-cta

**Comment by aeickhoff** [comment]
I already gave waffle.io a try early on, but the UI seemed really slow and unresponsive. I'll give it another look!

**Comment by ssokolow** [comment]
Huh. I didn't have that experience when I last used it. I wonder where the difference lies.

**Comment by chances** [comment]
What about the [Projects](https://github.com/citybound/citybound/projects) solution offered in GitHub directly?

**Comment by ssokolow** [comment]
@chances I thought about that too, but @aeickhoff seems to prefer to file tasks as issues so that every bug report doubles as a task. waffle.io would add a project board UI on top of that existing workflow.

**Comment by wopian** [comment]
GitHub Projects uses issues for tasks too.

**Comment by ssokolow** [comment]
Hmm, I did not know that.

Did they forget to mention that in the blog post which announced it? (That's as far as I've gotten with Projects so far, given that I haven't even finished bringing GitHub Issues up to spec with the rest of my data portability/exit strategy policy, which relies on everything else being stored in either the main repo (`git clone`) or the wiki (again, `git clone`).)

**Comment by wopian** [comment]
It was mentioned in the announcement blog post 😉 

>With Projects, you can manage work directly from your GitHub repositories. Create cards from Pull Requests, Issues or Notes and organize them into custom columns

![](https://cloud.githubusercontent.com/assets/3477155/18481731/44629a3e-79ab-11e6-8ce9-9ad5f07a135d.gif)

**Comment by ssokolow** [comment]
Ahh. I probably misinterpreted the text and was too hurried to toggle the Play/Pause status of the GIF.

(Even this time, if you hadn't prompted me to look closer, I would probably not have thought deeply enough about it to realize that "**move** things from the issue tracker to the project board" was a silly way to interpret it.)

**Comment by aeickhoff** [comment]
Closing, since I’m using github projects
