### ISSUE TITLE
UI crashes

### ISSUE THREAD

**Issue by zarte13** [citybound/citybound#325]
When undoing a buggy street UI crashed...
![screenshot_4](https://user-images.githubusercontent.com/34402486/46911442-10122200-cf2a-11e8-9c3c-a7f060001db1.png)
`Unhandled Rejection: Cannot read property 'message' of null
el.insertAdjacentHTML in ../src\citybound.js 17:67`

**Comment by tml** [comment]
Once I get this error, I am never able to load the project again - choosing it from the menu that appears when you pencil will immediately crash the UI with this same message.

**Comment by aeickhoff** [comment]
Probably a duplicate of #321, thanks for the report
