### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by ssokolow** [citybound/citybound#33]
Given that you want to be able to offer licensing other than the AGPL to people, you'll need to make sure any contributors understand the terms under which they must contribute.

The simplest way to do that is to add a `CONTRIBUTING.md` file, which will result in a hyperlinked "Please review the guidelines for contributing to this repository" banner above the "New ..." forms.

It's explained, including with a screenshot, in [this GitHub Blog post](https://github.com/blog/1184-contributing-guidelines).

**Comment by aeickhoff** [comment]
Thank you!
