### ISSUE TITLE
Crash when undoing 

### ISSUE THREAD

**Issue by zarte13** [citybound/citybound#334]
I know you are aware of this bug but this might help you fix it? 
So it's the bug when you undo and it crashes... How it happened to me: I started zoning an area then I undid part of it... And then when I undid the last node  then it crashed! Ok I hope this helps you resolve
[cb_last_error.txt](https://github.com/citybound/citybound/files/2825029/cb_last_error.txt)

**Comment by aeickhoff** [comment]
Thanks for the report! This is a duplicate of #321
