### ISSUE TITLE
InstancingNotSupported

### ISSUE THREAD

**Issue by simon1tan** [citybound/citybound#340]
Crashed. Nothing on screen.
Version: November 2017 Prototype 0.3.0
Win7 x64 SP1

Looks like I'm missing some files? It's not part the the exe.

Error loading Building Spawning settings: The system cannot find the file specif
ied. (os error 2) from "C:\\Users\\owner\\AppData\\Roaming\\ae play\\Citybound\\
0.3.0\\Building Spawning.json"
Error loading Plan Editing settings: The system cannot find the file specified.
(os error 2) from "C:\\Users\\owner\\AppData\\Roaming\\ae play\\Citybound\\0.3.0
\\Plan Editing.json"
Error loading Camera Control settings: The system cannot find the file specified
. (os error 2) from "C:\\Users\\owner\\AppData\\Roaming\\ae play\\Citybound\\0.3
.0\\Camera Control.json"

There is no data in those folders.

WHAT HAPPENED:
called `Result::unwrap()` on an `Err` value: InstancingNotSupported

WHERE IT HAPPENED:
at src\libcore\result.rs, line 906

WHERE EXACTLY:
stack backtrace:
   0:        0x13f5ebb72 - <no info>
   1:        0x13f5e9fd3 - <no info>
   2:        0x13f29bc17 - <no info>
   3:        0x13f613214 - <no info>
   4:        0x13f613019 - <no info>
   5:        0x13f612f62 - <no info>
   6:        0x13f612ed0 - <no info>
   7:        0x13f6194cf - <no info>
   8:        0x13f529f2e - <no info>
   9:        0x13f507d73 - <no info>
  10:        0x13f51519d - <no info>
  11:        0x13f53d743 - <no info>
  12:        0x13f533948 - <no info>
  13:        0x13f614342 - <no info>
  14:        0x13f537389 - <no info>
  15:        0x13f5358e3 - <no info>
  16:        0x13f53d8e3 - <no info>
  17:        0x13f3ee273 - <no info>
  18:        0x13f614342 - <no info>
  19:        0x13f366c95 - <no info>
  20:        0x13f407d27 - <no info>
  21:        0x13f6117cc - <no info>
  22:         0x770859cd - BaseThreadInitThunk

**Comment by aeickhoff** [comment]
Thanks for the report, but you're using a super old version, check out the live builds:

https://aeplay.org/citybound-livebuilds

I'll remove the releases from GitHub to avoid confusion
