### ISSUE TITLE
Self intersecting roads are not build

### ISSUE THREAD

**Issue by chdudek** [citybound/citybound#35]
If you build a road, which intersects with itself, it will not get build properly, but the 'blueprints' are still there. If another road blueprint intersects original road segment, the loop will show up, but with missing lanes (see screenshots).
![citybound_selfintersection1](https://cloud.githubusercontent.com/assets/12979837/21470343/c54d0aec-ca84-11e6-9027-8764b4ad31ac.png)
![citybound_selfintersection2](https://cloud.githubusercontent.com/assets/12979837/21470345/c578d6a4-ca84-11e6-90c8-c553f091e461.png)
![citybound_selfintersection3](https://cloud.githubusercontent.com/assets/12979837/21470347/c57a5f74-ca84-11e6-982b-e13dec46df2b.png)
![citybound_selfintersection4](https://cloud.githubusercontent.com/assets/12979837/21470346/c5791aa6-ca84-11e6-9950-bc707e08359e.png)
![citybound_selfintersection5](https://cloud.githubusercontent.com/assets/12979837/21470344/c577b544-ca84-11e6-8035-7aaa860cf4b1.png)

**Comment by aeickhoff** [comment]
I already had a last-minute solution for this, you can uncomment it here:

https://github.com/citybound/citybound/blob/795445e/src/game/lanes_and_cars/planning/plan_result_steps.rs#L69

But it caused a severe performance regression, that's why I removed it for the launch.
I'll look into it again!
