### ISSUE TITLE
Cannot scroll menu on macOS 10.14.4 in both Safari and Chrome

### ISSUE THREAD

**Issue by jcaudle** [citybound/citybound#352]
I just built the game on my MacBook Pro and when I run the site in Chrome or Safari, I cannot get the menu to scroll with my trackpad. I can use the spacebar to move the text or select text beyond what's visible and then grab the scroll bar to see more, but I'd expect the trackpad to move the text too.

P.S. — I'm super excited to get into this!

**Comment by aeplay** [comment]
Thanks for reporting, I already know the culprit!
