### ISSUE TITLE
UI crashes just for playing

### ISSUE THREAD

**Issue by zarte13** [citybound/citybound#354]
I was just playing, it was my 4th or 5th project and UI crashed

Crash:

> Citybound version: v0.1.2-784-gefaeb6a
> 
> Error: Rust WASM error: panicked at 'Expecting things to work in general: "Lot intersections too close to allow for padding"', src/libcore/result.rs:999:5
> Module.STDWEB_PRIVATE.to_js($1);Module.STDWEB_PRIVATE.from_js($0, in ../target/wasm32-unknown-unknown/release/cb_browser_ui.js 649:105
> Module.STDWEB_PRIVATE.to_js($1);Module.STDWEB_PRIVATE.from_js($0, in ../target/wasm32-unknown-unknown/release/cb_browser_ui.js 649:87
> cb_browser_ui::start::{{closure}}::h08b80e816b36cebe in wasm-function[278] 395:undefined
> std::panicking::rust_panic_with_hook::h6fb67c21cd72d854 in wasm-function[5393] 265:undefined
> std::panicking::continue_panic_fmt::h42680f75ce493543 in wasm-function[5392] 118:undefined
> rust_begin_unwind in wasm-function[5391] 3:undefined
> core::panicking::panic_fmt::h7748294af4ef73b0 in wasm-function[5442] 70:undefined
> core::result::unwrap_failed::hb0af2ff136003c16 in wasm-function[3886] 106:undefined
> cb_simulation::land_use::buildings::architecture::build_building::h66fa714432fb9b0e in wasm-function[3235] 14726:undefined
> ::on_building_constructed::h32be5bb441de2f51 in wasm-function[757] 119:undefined

Console:
`V6([::1]:56592) loaded page
Got connection from [::1]:56597, shaking hands...
...machine ID 1 connected!
Member PrototypeID(13740794223627062228) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(7129859722274174848) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(4992763020702639069) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!
Member PrototypeID(14254849049777566956) already exists in grid!

Member PrototypeID(14254849049777566956) already exists in grid!

Member PrototypeID(14254849049777566956) already exists in grid!

Member PrototypeID(14254849049777566956) already exists in grid!

Member PrototypeID(14254849049777566956) already exists in grid!
V6([::1]:56595) loaded page
Closed connection to Machine ID 1 while receiving: IO error: Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte. (os error 10053)
Got connection from [::1]:56641, shaking hands...
...machine ID 1 connected!
V6([::1]:56595) loaded page
Closed connection to Machine ID 1 while receiving: IO error: Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte. (os error 10053)
Got connection from [::1]:56642, shaking hands...
...machine ID 1 connected!
Member PrototypeID(14254849049777566956) already exists in grid!`

**Comment by aeplay** [comment]
That's a problem with the new building generation code, thanks for reporting!

**Comment by aeplay** [comment]
This shouldn't result in a hard crash anymore in the newest version.
