### ISSUE TITLE
Error when trying to spawn cars

### ISSUE THREAD

**Issue by woubuc** [citybound/citybound#36]
Whenever I press `c` to spawn cars, as it says on the [wiki](https://github.com/citybound/citybound/wiki/Road-%26-Traffic-Prototype-1#spawning-cars), I get an error in the top left corner.

    SIMULATION PANIC:
    attempt to calculate the remainder with a divisor of zero

The console output:

    thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero', lib\kay\src\slot_map.rs:73
    note: Run with 'RUST_BACKTRACE=1' for a backtrace.
    Simulation Panic!
    "attempt to calculate the remainder with a divisor of zero"

I've tried some different basic road combinations (tried with and without selecting roads) but all of them resulted in the same error. See attached screenshots.

Version: 0.1.0
Platform: Windows 7 x64

![citybound-spawn-1](https://cloud.githubusercontent.com/assets/1015540/21470471/4414460a-ca8b-11e6-8ccc-3c208b3a3aad.PNG)
![citybound-spawn-2](https://cloud.githubusercontent.com/assets/1015540/21470472/441484ee-ca8b-11e6-8baf-ef0e28a338ca.PNG)
![citybound-spawn-3](https://cloud.githubusercontent.com/assets/1015540/21470473/44179c38-ca8b-11e6-9ee1-e138b652e56c.PNG)
![citybound-spawn-4](https://cloud.githubusercontent.com/assets/1015540/21470508/86591cce-ca8c-11e6-99ba-4a9aa1f2776c.PNG)

**Comment by aeickhoff** [comment]
You need to build the roads first, using the Return key! I'll keep the issue to make sure I'll fix the UI.

**Comment by woubuc** [comment]
Whoops, yeah now it works. Maybe you could add this info to the controls page on the wiki as well.

**Comment by ssokolow** [comment]
...and, of course, handle that case so it doesn't result in a simulation panic.

(Perhaps an error message like "Cannot spawn cars. No roads constructed. (Did you press Enter to finalize your plans?)"

**Comment by aeickhoff** [comment]
Of course!

**Comment by aeickhoff** [comment]
Note to self: there is a more serious, underlying bug here: sending a broadcast message to a swarm with no members shouldn't cause such errors.
