### ISSUE TITLE
Where is the developer?

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [citybound/citybound#389]
Its been radio silent for over a year on both the website, and this repository. What gives?

**Comment by tomholford** [comment]
Based on Anselm's [Twitter feed](https://twitter.com/ae_play/), [web site](
https://aeplay.org/), and commit history, it appears the current focus is a note-taking / developer productivity tool, perhaps named Garden.

**Comment by XtremeOwnageDotCom** [comment]
Just make sure he didn't fall off the face of the planet! I have a news feed setup for this project, and it's been quiet for awhile. Thanks for finding that.
