### ISSUE TITLE
how to buil 

### ISSUE THREAD

**Issue by dd123-a** [citybound/citybound#411]
I don't know why, but according to the wiki compilation, I can't run it correctly and will get an error
![image](https://github.com/user-attachments/assets/aa703751-ee34-4c16-a304-175dc04b0134)

**Comment by chances** [comment]
@dd123-a How did you resolve this issue?

**Comment by dd123-a** [comment]
> @dd123-a How did you resolve this issue?

I downloaded an alternative version of cargo-web (0.6.25) which solved this issue, but I anticipate many more problems ahead. Even after making numerous modifications and obtaining the exe file, it still won't run. This project seems to be dead. If you have succeeded, please share the relevant details.
