### ISSUE TITLE
FAQ on website links to disabled reddit wiki

### ISSUE THREAD

**Issue by kasbah** [citybound/citybound#42]
[cityboundsim.com](http://cityboundsim.com) links to http://wiki.cityboundsim.com/FAQ which doesn't exist.

**Comment by MiniDigger** [comment]
it links to a reddit wiki for me that has been disabled
https://www.reddit.com/r/Citybound/wiki/FAQ

**Comment by kasbah** [comment]
While we are on links from the website to [the patreon](https://www.patreon.com/citybound). Are the other donation mechanisms preferred?

**Comment by aeickhoff** [comment]
Just didn't have time yet! I'll fix all of that!

**Comment by aeickhoff** [comment]
Migrated the FAQ and replaced donation options with Patreon
