### ISSUE TITLE
Game Crashing when Constructing Roads

### ISSUE THREAD

**Issue by jlga** [citybound/citybound#44]
Game crashed when building this roadstructure (pressing `return`)
Running on Win10 Anniversary
![cityboundcrash](https://cloud.githubusercontent.com/assets/17816133/21472498/dbbde31a-cadd-11e6-9492-0a6702149f2f.PNG)

Edit: It crashes whenever two roads cross, one or two roads that do not cross work fine

**Comment by aeickhoff** [comment]
Is there an error message in the terminal window that starts with the game when you get this error?

**Comment by jlga** [comment]
I can't belive it, but I can't reproduce it anymore, I swear it happened consistently before, but now it doesn't anymore. I did not restart my PC or did anything else that could influence it. I am sorry.
