### ISSUE TITLE
Project Managment

### ISSUE THREAD

**Issue by tsteinholz** [citybound/citybound#46]
It would be really helpful if the projects tab was used to make an Agile style project board. The categories could be Backlog, In-Progress, Testing, and Done. Then each card could link to an issue which could have an assignee or something. That would make development on this project easier for new developers.

**Comment by aeickhoff** [comment]
I would rather have as little process-overhead as possible. As soon as my current workflow of just committing to master becomes too chaotic (that will probably be soon), I will start doing my own development as pull-requests, which should already be enough indication of what is currently worked on. I'll close this issue for now unless there is protest :)
