### ISSUE TITLE
Fails to launch on OS X El Capitan 10.11.6 via application package

### ISSUE THREAD

**Issue by chances** [citybound/citybound#49]
The app fails to launch via the .app package on OS X El Capitan 10.11.6 claiming:

```
You have OS X 10.11.6. The application requires OS X 10.12 or later.
```

However, I _can_ launch Citybound by manually running the executable within the application package. Probably a simple issue with the package metadata.

**Comment by aeickhoff** [comment]
I'm new to app bundling, I probably need to change something in Info.plist, anyone know what?

**Comment by chances** [comment]
Apple Dev Docs:

- [Application Bundles](https://developer.apple.com/library/content/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW13)
- [About Information Property List Files](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html)

**Comment by chances** [comment]
It seems you'll have to set the [deployment target](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/ConfiguringYourApp/ConfiguringYourApp.html#//apple_ref/doc/uid/TP40012582-CH28-SW21) to the lowest operating system version that the app can run on.

I found a [StackOverflow answer](http://stackoverflow.com/a/6594992/1363247) related to the issue.

**Comment by aeickhoff** [comment]
@chances can you try this bundle: I set the Minimum System Version to something much older
[Citybound.app.zip](https://github.com/citybound/citybound/files/693324/Citybound.app.zip)

**Comment by aeickhoff** [comment]
@chances what about this bundle:
[citybound.app.zip](https://github.com/citybound/citybound/files/694862/citybound.app.zip)

**Comment by chances** [comment]
@aeickhoff Works great on my machine!

**Comment by aeickhoff** [comment]
Thank you!
