### ISSUE TITLE
Cars Despawn while merging 

### ISSUE THREAD

**Issue by seeaya** [citybound/citybound#60]
Cars disappear near merging lanes, or while changing lanes after merging 
![initial ss](https://cloud.githubusercontent.com/assets/11371648/21511048/a63d3458-cc58-11e6-9c0a-200568f7500d.png)
![final ss](https://cloud.githubusercontent.com/assets/11371648/21511051/acbb0c2e-cc58-11e6-9b6e-5e358365ca33.png)
Often they appear to be changing lanes into a non-existing lane before they despawn

**Comment by jlga** [comment]
I think, that it is just the cars reaching their destination

**Comment by seeaya** [comment]
I was under the impression that the destinations were only at the roads' end points, but I could be wrong

**Comment by Herbstein** [comment]
You would have to read through the code to determine that, but I do agree with @jlga that it's probably the cars reaching their destination.

**Comment by aeickhoff** [comment]
Confirmed: they are just reaching their destination. Of course that will become nicer with actual driveways or parking spaces!
