### ISSUE TITLE
MacOS no window

### ISSUE THREAD

**Issue by herrDerToene** [citybound/citybound#66]
Citybound worked the first time I started it. Until I clicked on a road... Road to Death literally...
The window disappeared and since then won't show up again after restarting Citybound or my mac (MacBook Pro Retina 13" Late 2013, macOS 10.12.2). The github page is not opening too.

I'm not sure if I did run Citybound in full screen and if that might have been the killer.

**Comment by chances** [comment]
#34 has more details related to this issue.
