### ISSUE TITLE
Error on resolving dependencies

### ISSUE THREAD

**Issue by Herbstein** [citybound/citybound#75]
I can't build the project after #53 was merged.

`Updating registry 'https://github.com/rust-lang/crates.io-index'`
`error: failed to select a version for 'serde' (required by 'citybound'):`
`version 0.8.21 in use by serde v0.8.21`
`possible versions to select: 0.8.16`

I've tried cleaning the repository with `cargo clean`, and completely rebuilding thereafter. That didn't change anything.

This, weirdly, doesn't happen in a completely new clone. I haven't changed anything in the original repo.

**Comment by aeickhoff** [comment]
Does cargo clean also delete Cargo.lock?

**Comment by Herbstein** [comment]
Damn. I just deleted my local copy with the error, and cloned my own fork instead. I'll close the issue.
