### ISSUE TITLE
Kay Architecture Improvements (Discussions)

### ISSUE THREAD

**Issue by aeickhoff** [citybound/citybound#76]
I already have some goals of my own for how to improve kay, but let's use this issue to discuss, I'll add my ideas as we go.

**Comment by kingoflolz** [comment]
Here is how I think threading can be added:
- each thread will have a thread local outbox, where messages are queued
- each chunk in each swarm will have a local inbox
- multiple threads can process the inbox of each chunk in parallel, adding the messages they send to their thead local outbox
- one single thread aggregates all the thread local out boxes and moves them to the inboxes

**Comment by aeickhoff** [comment]
My plan for threading was somewhat simpler:

- make Inbox a correct, lock-free single-reader/multi-writer queue (multiple threads can enqueue messages to it whenever, without acquiring a lock)
- one Inbox per actor type (maybe even chunk as you suggested, for swarms with a lot of actors)
- one thread per CPU core
- each thread chooses an actor type / chunk, get's exclusive write access to it and processes all messages

**Comment by kingoflolz** [comment]
Hrm I think that is probably a better plan, although I don't think that would be deterministic, which would be important for multiplayer

**Comment by kingoflolz** [comment]
I think I can make my plan deterministic by having a per chunk outbox, and the traversing the outboxes in a deterministic order. The problem is that mpsc queue has non deterministic ordering between different threads queueing.

**Comment by aeickhoff** [comment]
I gave up on global determinism as a goal, since that will be almost impossible once you scale the simulation beyond one computer and you have to deal with network latencies. What is important (and not guaranteed yet) is that if you send several messages from Actor A to Actor B, that they arrive in the same order. That's the most you can get (and for example also what highly concurrent Erlang chose as its only message sending guarantee).

**Comment by kingoflolz** [comment]
Hrm, I assumed that you will be doing something similar to most rts games, where essentially only the input is sent between the players.
After re reading your blog post I see you are planning to allow multiple computers to distribute the simulation when making it multiplayer by sending messages across machine boundaries over the internet. 
In that case, how do you send all the state back to the rendering machine so that it can show not just its own chunks, but also chunks on other machines? 
P.S. I think it is much easier to start with the goal  of deterministic simulation if debug issues as they come up

**Comment by aeickhoff** [comment]
The renderer would send render messages not only to local actors but also remote ones, basically "streaming geometry" as necessary.

I would even say it the other way around, I want to try to not depend on determinism at all to get acceptable results.

**Comment by kingoflolz** [comment]
If you have 100k cars distributed between 2 computers, the data rate would 50k*(2 + 4*3)*60*8 bits per second, which is ~300 Mbps. Wouldn't that rule out playing over the internet?

**Comment by aeickhoff** [comment]
That's exactly the extreme case, I don't think it will be necessary to render that many cars remotely (you could just display less remote cars)

**Comment by kingoflolz** [comment]
Wouldn't the definition of remote depend on your camera location, not the machine or is running on? So you might still have to show alot of remote (machine wise) the cars.

**Comment by aeickhoff** [comment]
I mean there could be some logic that limits the number of rendered cars you send to a remote renderer

**Comment by kingoflolz** [comment]
I think even 1k remote cars would saturate most internet connections (most people esp in the us don't have 6mbps upload) and I think it would be easy to zoom out to such a level where you cab see 1k cars but the individual car behaviour is still visible (which means you still need to render them)

**Comment by aeickhoff** [comment]
Does that already take into account dead reckoning? I think interpolating cars until there is fresh remote information is quite feasible. And btw, if all lane information is synced, the information per car is pretty much only [car id, 1D position along lane]

**Comment by kingoflolz** [comment]
No, it is just the raw, full positional data every frame (which is the worst case). With dead reckoning, I think it would be reasonable. However, I think it will be difficult to make the transition between local and remote simulation smooth, and also, how would saving work as half the save is on one computer. Would you just sync it over and piece of together? Could they cause any consistency issues? Another unrelated and probably unimportant issue is that players can easily chat in multiplayer grabs.

**Comment by kingoflolz** [comment]
On a unrelated note, I think it might be possible to remove the need for the invalid ID type, and use https://doc.rust-lang.org/core/nonzero/struct.NonZero.html to have zero overhead Option<ID> which better represent the semantics

**Comment by aeickhoff** [comment]
yes, that would be very good, then we just need to make sure that type-ids start from 1 so a completely zero'd ID can have this meaning?

**Comment by kingoflolz** [comment]
yeah, I think so.

Also, should we make THE_SYSTEM an optional pointer instead of a nullable pointer? Seems more rustic that way

**Comment by aeickhoff** [comment]
That would mean an additional branch every time we try do do something with it, when we already know for sure that it exists "eternally"

**Comment by kingoflolz** [comment]
Fair enough, its not used in that many places either

**Comment by kingoflolz** [comment]
See #89

**Comment by kingoflolz** [comment]
Another random idea, when an actor overflows their dynamic part and need to relocate, instead of copying the whole dynamic part into a heap buffer, point it to the start of its dynamic position in a slot in the next chunk size up, moving it there when it is actually relocated.

**Comment by aeickhoff** [comment]
Makes sense, but the problem is that an actor might contain several dynamic fields which might or might not overflow during actor update - so you don't know ahead of time which "higher sized slot" is of a correct size and how the dynamic fields should be layouted within it.

**Comment by kingoflolz** [comment]
Maybe this is borderlining on too complex, but you *could* relayout every dynamic field within the struct with every relocation, with the items that need to be expanded going first.

e.g. you have:
```
struct whatever{
a: CVec<whatever>,
b: CVec<whatever>,
c: CVec<whatever>,
}
```
and B is pushed during the update and needs to reallocate, it will ask the multiSizedArena for a bigger location and be placed at slotStart+staticSize+dynamicSize(0). If then C wants to be expanded, it will be placed at slotStart+staticSize+dynamicSize(dynamic size of B). Then when it is relocated, the static part will be moved and then a will be placed at slotStart+staticSize+dynamicSize(dynamic size of B+C)

**Comment by aeickhoff** [comment]
I see, but that *is* very complicated. Maybe something to try at a later point - I think we can find lower-hanging optimisations than this.

But isn't it cool that we can discuss and even experiment with such optimisations without the game logic even noticing? :)

**Comment by aeickhoff** [comment]
Closing this issue, since we now have [Gitter](https://gitter.im/citybound/Lobby) for conversational discussions. I'll create future issues to document any concrete plans that come from discussions there.
