### ISSUE TITLE
No place to do general discussion

### ISSUE THREAD

**Issue by Herbstein** [citybound/citybound#77]
We should set up a place where we can do general conversations about the project without creating a new issue. A quick, temporary solution could be a Discord server.

**Comment by aeickhoff** [comment]
Why not the subreddit? Chat is too temporary for me...

**Comment by Herbstein** [comment]
I just thought that the subreddit was intended as being more user-facing.

**Comment by aeickhoff** [comment]
I would even encourage user- and contributor-communities to be mixed, so feel free to discuss development-related things there!

**Comment by Herbstein** [comment]
Awesome. I'll do that instead.
