### ISSUE TITLE
Add listeners for builtin MacOS gestures

### ISSUE THREAD

**Issue by aeplay** [citybound/citybound#8]
Add listeners for magnification and rotation in
- https://github.com/servo/cocoa-rs/blob/master/src/appkit.rs
- https://github.com/tomaka/glutin/blob/master/src/api/cocoa/mod.rs

Do so as a fork first, then pull-request to the original projects with an issue there

**Comment by chances** [comment]
https://developer.apple.com/reference/appkit/nsmagnificationgesturerecognizer

**Comment by chances** [comment]
Glutin's [window.poll_events()](https://github.com/citybound/citybound/blob/master/src/core/ui.rs#L517) returns a [winit](https://crates.io/crates/winit) `PollEventsIterator`. The winit library currently only supports rudimentary touch events.

Seems like the best route would be to contribute new gesture primitives to [servo/cocoa-rs](https://github.com/servo/cocoa-rs), integrate that with winit's macOS bindings to produce gesture event types, integrate that into a new version of glutin, and then finally integrate a new version of glutin into Citybound.

**Comment by aeickhoff** [comment]
Thanks for the research! Landing it in winit would be enough, since glutin as a graphics backend doesn't have a bright future anyways and I'll probably switch to gfx-rs!

**Comment by chances** [comment]
It looks like cocoa-rs already has [gesture primitives](https://github.com/servo/cocoa-rs/blob/5b9a27e4cb1f8ec805da424cc0cdae7ff475fc8f/src/appkit.rs#L1966) in its AppKit bidings. :smile:

Might now only have to add Gesture event types to winit similarly as for [`NSEventTypePressure`](https://github.com/tomaka/winit/blob/41ac24b1073220193bc45d3f7271f3a57d949357/src/platform/macos/mod.rs#L824).

**Comment by chances** [comment]
tomaka/winit#54

**Comment by chances** [comment]
@aeickhoff Considering the new web-based frontend, this just became a lot easier.

[Detecting multi-touch trackpad gestures in JavaScript](https://medium.com/@auchenberg/detecting-multi-touch-trackpad-gestures-in-javascript-a2505babb10e)

### Pinch-to-zoom

> You can detect a pinch-to-zoom gesture [by] listening for the `wheel` event, where the `e.deltaY` value represents your zoom/scale factor when the `e.ctrlKey` is set.

### Pan

It seems these can be equivalently mapped from regular `wheel` events. Perhaps only when the user agent is macOS?

-----

I'm not sure about the Rotate gesture, though.
