### ISSUE TITLE
Active plan doesn't "turn gray" when finished. 

### ISSUE THREAD

**Issue by Herbstein** [citybound/citybound#82]
I'm not sure what the internal terminology is. When you're actively manipulating a road section it'll be blue and yellow. When you double-click it's supposed to turn gray. This doesn't happen anymore. Implementing roads aren't impacted.

I think the gray version of the section might be rendered under the active road section. There seems to be a small double-layering that's only noticeable when the frame rate is low (~400ms per frame). I haven't looked at the code, but maybe the gray version is one frame behind the colored version?

**Comment by aeickhoff** [comment]
Actually, you're never supposed to see the grey version and that's a bug.
I created an issue: #84
