### ISSUE TITLE
Camera movement is completely dependent on framerate

### ISSUE THREAD

**Issue by Herbstein** [citybound/citybound#90]
The movement code has no concept of frame rate. That means someone running the game at 60fps can move farther in a second than someone running it at 30fps. It's not a massive issue for the small demos, but it's vital when the game gets any meaningful size.

I personally like the way the Unity3d engine does this. There's a static class called `Time` that contains the `Time.deltaTime` variable. This is the fraction of a second that has passed since the last frame. The current movement code should barely be changed. Like so: 

`Renderer::id() << MoveEye {scene_id: 0, movement: ::monet::Movement::Yaw(delta * delta_time)};`

It's also much easier to reason about the movement speed like this. You're simply moving `delta` units per second.

**Comment by aeickhoff** [comment]
So far, only simulated things received a delta_time, but it would be nice if rendering-related things could receive a frame_delta_time, independent of the simulation-time (so it also works when the simulation is paused etc.)

This is one aspect for #91

**Comment by aeickhoff** [comment]
Since I captured it in #91, I will close this
